language: c

compiler:
        - gcc
        - clang

addons:
        apt:
                packages:
                        - git
                        - autoconf
                        - libtool
                        - pkg-config
                        - gperf
                        - ncurses-dev
                        - uuid
                        - uuid-dev
                        - sqlite3
                        - libsqlite3-dev
script: mkdir build && cd build && cmake .. && make
