#ifndef _MODULES_SYSCTL_OPTIONS_H_
#define _MODULES_SYSCTL_OPTIONS_H_

enum {
	OPTS_SYSCTL_DROP_CACHES_INIT_PRE = 0x01,
	OPTS_SYSCTL_DROP_CACHES_INIT = 0x02,
	OPTS_SYSCTL_DROP_CACHES_INIT_POST = 0x04,
	OPTS_SYSCTL_DROP_CACHES_RUN_PRE = 0x08,
	OPTS_SYSCTL_DROP_CACHES_RUN = 0x10,
	OPTS_SYSCTL_DROP_CACHES_RUN_POST = 0x20,
	OPTS_SYSCTL_DROP_CACHES_PARSE_RESULTS = 0x40,
	OPTS_SYSCTL_DROP_CACHES_EXIT_PRE = 0x80,
	OPTS_SYSCTL_DROP_CACHES_EXIT = 0x100,
	OPTS_SYSCTL_DROP_CACHES_EXIT_POST = 0x200,
};

struct options_sysctl_drop_caches {
	int active_functions;
};

#endif  /* _MODULES_SYSCTL_OPTIONS_H_ */
